<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="characters" tilewidth="16" tileheight="16" tilecount="151" columns="16">
 <image source="characters.png" width="256" height="160"/>
 <tile id="0" type="player_down_0"/>
 <tile id="1" type="player_up_0"/>
 <tile id="2" type="player_down_1"/>
 <tile id="3" type="player_up_1"/>
 <tile id="4" type="player_down_2"/>
 <tile id="5" type="player_up_2"/>
 <tile id="6" type="player_side_0"/>
 <tile id="7" type="player_side_1"/>
 <tile id="8" type="player_side_2"/>
 <tile id="9" type="rat_0"/>
 <tile id="10" type="rat_1"/>
 <tile id="11" type="rat_grey_0"/>
 <tile id="12" type="rat_grey_1"/>
 <tile id="13" type="bat_brown_0"/>
 <tile id="14" type="bat_brown_1"/>
 <tile id="15" type="bat_green_0"/>
 <tile id="16" type="bat_green_1"/>
 <tile id="17" type="bat_red_0"/>
 <tile id="18" type="bat_red_1"/>
 <tile id="19" type="beetle_0"/>
 <tile id="20" type="beetle_1"/>
 <tile id="21" type="beetle_bronze_0"/>
 <tile id="22" type="beetle_bronze_1"/>
 <tile id="23" type="worm_0"/>
 <tile id="24" type="worm_1"/>
 <tile id="25" type="mound_0"/>
 <tile id="26" type="snake_0"/>
 <tile id="27" type="snake_1"/>
 <tile id="28" type="snake_red_0"/>
 <tile id="29" type="snake_red_1"/>
 <tile id="30" type="wasp_0"/>
 <tile id="31" type="wasp_1"/>
 <tile id="32" type="scorpion_0"/>
 <tile id="33" type="scorpion_1"/>
 <tile id="34" type="scorpion_black_0"/>
 <tile id="35" type="scorpion_black_1"/>
 <tile id="36" type="jackal_0"/>
 <tile id="37" type="jackal_1"/>
 <tile id="38" type="sentinel_0"/>
 <tile id="39" type="sentinel_1"/>
 <tile id="40" type="sandworm_0"/>
 <tile id="41" type="sandworm_1"/>
 <tile id="42" type="mound_sand_0"/>
 <tile id="43" type="frog_0"/>
 <tile id="44" type="frog_1"/>
 <tile id="45" type="frog_2"/>
 <tile id="46" type="toad_0"/>
 <tile id="47" type="toad_1"/>
 <tile id="48" type="mosquito_0"/>
 <tile id="49" type="mosquito_1"/>
 <tile id="50" type="mender_0"/>
 <tile id="51" type="mender_1"/>
 <tile id="52" type="chief_mender_0"/>
 <tile id="53" type="chief_mender_1"/>
 <tile id="54" type="plague_rat_0"/>
 <tile id="55" type="plague_rat_1"/>
 <tile id="56" type="bog_lurker_0"/>
 <tile id="57" type="bog_lurker_1"/>
 <tile id="58" type="mound_bog_0"/>
 <tile id="59" type="ooze_0"/>
 <tile id="60" type="ooze_1"/>
 <tile id="61" type="boat_0"/>
 <tile id="62" type="wren_0"/>
 <tile id="63" type="wren_1"/>
 <tile id="64" type="click_0"/>
 <tile id="65" type="click_1"/>
 <tile id="66" type="unit7_0"/>
 <tile id="67" type="unit7_1"/>
 <tile id="68" type="ilse_0"/>
 <tile id="69" type="ilse_1"/>
 <tile id="70" type="queen_0"/>
 <tile id="71" type="queen_1"/>
 <tile id="72" type="ossa_0"/>
 <tile id="73" type="ossa_1"/>
 <tile id="74" type="clack_0"/>
 <tile id="75" type="clack_1"/>
 <tile id="76" type="mandi_0"/>
 <tile id="77" type="mandi_1"/>
 <tile id="78" type="nettle_0"/>
 <tile id="79" type="nettle_1"/>
 <tile id="80" type="wick_0"/>
 <tile id="81" type="wick_1"/>
 <tile id="82" type="unit9_0"/>
 <tile id="83" type="unit9_1"/>
 <tile id="84" type="pip_0"/>
 <tile id="85" type="pip_1"/>
 <tile id="86" type="mara_0"/>
 <tile id="87" type="mara_1"/>
 <tile id="88" type="slash_0"/>
 <tile id="89" type="slash_1"/>
 <tile id="90" type="slash_2"/>
 <tile id="91" type="hit_0"/>
 <tile id="92" type="hit_1"/>
 <tile id="93" type="heal_plus"/>
 <tile id="94" type="tongue"/>
 <tile id="95" type="tongue_tip"/>
 <tile id="96" type="shot_acid"/>
 <tile id="97" type="shot_spark"/>
 <tile id="98" type="shot_arrow"/>
 <tile id="99" type="shot_rock"/>
 <tile id="100" type="shot_fire"/>
 <tile id="101" type="shot_sand"/>
 <tile id="102" type="shot_poison"/>
 <tile id="103" type="explosion_0"/>
 <tile id="104" type="explosion_1"/>
 <tile id="105" type="explosion_2"/>
 <tile id="106" type="seal_0"/>
 <tile id="107" type="seal_1"/>
 <tile id="108" type="ape_0"/>
 <tile id="109" type="ape_1"/>
 <tile id="110" type="shade_0"/>
 <tile id="111" type="shade_1"/>
 <tile id="112" type="moth_0"/>
 <tile id="113" type="moth_1"/>
 <tile id="114" type="icicle_0"/>
 <tile id="115" type="icicle_1"/>
 <tile id="116" type="target_snowman_0"/>
 <tile id="117" type="target_snowman_1"/>
 <tile id="118" type="target_phantom_0"/>
 <tile id="119" type="target_phantom_1"/>
 <tile id="120" type="target_puck_0"/>
 <tile id="121" type="target_puck_1"/>
 <tile id="122" type="target_hare_0"/>
 <tile id="123" type="target_hare_1"/>
 <tile id="124" type="bat_frost_0"/>
 <tile id="125" type="bat_frost_1"/>
 <tile id="126" type="wolf_0"/>
 <tile id="127" type="wolf_1"/>
 <tile id="128" type="crawler_0"/>
 <tile id="129" type="crawler_1"/>
 <tile id="130" type="sentinel_frost_0"/>
 <tile id="131" type="sentinel_frost_1"/>
 <tile id="132" type="hask_0"/>
 <tile id="133" type="hask_1"/>
 <tile id="134" type="sleet_0"/>
 <tile id="135" type="sleet_1"/>
 <tile id="136" type="tamsin_0"/>
 <tile id="137" type="tamsin_1"/>
 <tile id="138" type="ysolde_0"/>
 <tile id="139" type="ysolde_1"/>
 <tile id="140" type="grizzle_0"/>
 <tile id="141" type="grizzle_1"/>
 <tile id="142" type="brann_0"/>
 <tile id="143" type="brann_1"/>
 <tile id="144" type="vey_0"/>
 <tile id="145" type="vey_1"/>
 <tile id="146" type="shot_icicle"/>
 <tile id="147" type="shot_snowball"/>
 <tile id="148" type="shot_shard"/>
 <tile id="149" type="shot_frost"/>
 <tile id="150" type="shot_dirge"/>
</tileset>
