<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="items" tilewidth="16" tileheight="16" tilecount="66" columns="16">
 <image source="items.png" width="256" height="80"/>
 <tile id="0" type="fist"/>
 <tile id="1" type="rusty_knife"/>
 <tile id="2" type="wooden_club"/>
 <tile id="3" type="bronze_spear"/>
 <tile id="4" type="bone_bow"/>
 <tile id="5" type="spark_caster"/>
 <tile id="6" type="leather_vest"/>
 <tile id="7" type="bronze_cuirass"/>
 <tile id="8" type="lucky_shell"/>
 <tile id="9" type="vigor_ring"/>
 <tile id="10" type="firefly_jar"/>
 <tile id="11" type="water_bottle"/>
 <tile id="12" type="fig"/>
 <tile id="13" type="glowcap_item"/>
 <tile id="14" type="bandage"/>
 <tile id="15" type="herb_tea"/>
 <tile id="16" type="eternal_lantern"/>
 <tile id="17" type="cartographer_lens"/>
 <tile id="18" type="climbing_claws"/>
 <tile id="19" type="satchel"/>
 <tile id="20" type="energy_core"/>
 <tile id="21" type="ancient_fragment"/>
 <tile id="22" type="notebook"/>
 <tile id="23" type="flashlight"/>
 <tile id="24" type="bronze_key"/>
 <tile id="25" type="arrows"/>
 <tile id="26" type="bomb"/>
 <tile id="27" type="prickly_pear"/>
 <tile id="28" type="waterskin"/>
 <tile id="29" type="lexicon_page"/>
 <tile id="30" type="tide_lexicon"/>
 <tile id="31" type="everflowing_amphora"/>
 <tile id="32" type="eye_of_storm"/>
 <tile id="33" type="sandstride_anklets"/>
 <tile id="34" type="bronze_khopesh"/>
 <tile id="35" type="sun_mace"/>
 <tile id="36" type="desert_wraps"/>
 <tile id="37" type="sun_amulet"/>
 <tile id="38" type="beaked_mask"/>
 <tile id="39" type="ferry_skiff"/>
 <tile id="40" type="menders_coil"/>
 <tile id="41" type="bezoar"/>
 <tile id="42" type="swamp_salve"/>
 <tile id="43" type="nettle_tonic"/>
 <tile id="44" type="bog_lily"/>
 <tile id="45" type="physician_seal"/>
 <tile id="46" type="harpoon"/>
 <tile id="47" type="bronze_scalpel"/>
 <tile id="48" type="oilskin_coat"/>
 <tile id="49" type="tide_pearl"/>
 <tile id="50" type="thermometer"/>
 <tile id="51" type="watch_torch"/>
 <tile id="52" type="icicle_sling"/>
 <tile id="53" type="rimeshard"/>
 <tile id="54" type="watch_halberd"/>
 <tile id="55" type="dirge_bell"/>
 <tile id="56" type="icicle"/>
 <tile id="57" type="fur_cloak"/>
 <tile id="58" type="watch_plate"/>
 <tile id="59" type="hearthstone"/>
 <tile id="60" type="sorrels_snowflake"/>
 <tile id="61" type="hollowcap"/>
 <tile id="62" type="warm_broth"/>
 <tile id="63" type="rime_crampons"/>
 <tile id="64" type="watch_ember"/>
 <tile id="65" type="sleepless_eye"/>
</tileset>
