<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="town-tileset" tilewidth="16" tileheight="16" spacing="1" tilecount="132" columns="12">
 <image source="town-tileset.png" width="203" height="186"/>
 <tile id="0" type="grass"/>
 <tile id="1" type="grass_tufts"/>
 <tile id="2" type="grass_flowers"/>
 <tile id="3" type="pine_orange"/>
 <tile id="4" type="pine_green"/>
 <tile id="5" type="bush_big"/>
 <tile id="12" type="path_tl"/>
 <tile id="13" type="path_t"/>
 <tile id="14" type="path_tr"/>
 <tile id="15" type="tree_orange"/>
 <tile id="16" type="tree_green"/>
 <tile id="17" type="sprout"/>
 <tile id="24" type="path_l"/>
 <tile id="25" type="path"/>
 <tile id="26" type="path_r"/>
 <tile id="27" type="pine_orange_tall"/>
 <tile id="28" type="pine_green_tall"/>
 <tile id="29" type="mushrooms"/>
 <tile id="36" type="path_bl"/>
 <tile id="37" type="path_b"/>
 <tile id="38" type="path_br"/>
 <tile id="39" type="path_inner_tl"/>
 <tile id="40" type="path_inner_tr"/>
 <tile id="41" type="path_inner_br"/>
 <tile id="42" type="path_inner_bl"/>
 <tile id="43" type="stone_circle"/>
 <tile id="44" type="fence_tl"/>
 <tile id="45" type="fence_t"/>
 <tile id="46" type="fence_tr"/>
 <tile id="47" type="fence_v_top"/>
 <tile id="48" type="roof_blue_tl"/>
 <tile id="49" type="roof_blue_t"/>
 <tile id="50" type="roof_blue_tr"/>
 <tile id="52" type="roof_red_tl"/>
 <tile id="53" type="roof_red_t"/>
 <tile id="54" type="roof_red_tr"/>
 <tile id="56" type="fence_l"/>
 <tile id="58" type="fence_r"/>
 <tile id="59" type="fence_v"/>
 <tile id="60" type="roof_blue_bl"/>
 <tile id="61" type="roof_blue_b"/>
 <tile id="62" type="roof_blue_br"/>
 <tile id="64" type="roof_red_bl"/>
 <tile id="65" type="roof_red_b"/>
 <tile id="66" type="roof_red_br"/>
 <tile id="68" type="fence_bl"/>
 <tile id="70" type="fence_br"/>
 <tile id="71" type="fence_v_bottom"/>
 <tile id="72" type="wall_wood_l"/>
 <tile id="73" type="wall_wood"/>
 <tile id="75" type="wall_wood_r"/>
 <tile id="76" type="wall_stone_l"/>
 <tile id="77" type="wall_stone"/>
 <tile id="79" type="wall_stone_r"/>
 <tile id="80" type="fence_h_left"/>
 <tile id="81" type="fence_h"/>
 <tile id="82" type="fence_h_right"/>
 <tile id="83" type="sign"/>
 <tile id="84" type="window_wood"/>
 <tile id="85" type="door_wood"/>
 <tile id="88" type="window_stone"/>
 <tile id="89" type="door_stone"/>
 <tile id="93" type="coin"/>
 <tile id="95" type="target"/>
 <tile id="96" type="slab_tl"/>
 <tile id="97" type="slab_t"/>
 <tile id="98" type="slab_tr"/>
 <tile id="103" type="ladder_down"/>
 <tile id="105" type="bomb"/>
 <tile id="108" type="slab_l"/>
 <tile id="109" type="slab"/>
 <tile id="110" type="slab_r"/>
 <tile id="115" type="pickaxe"/>
 <tile id="117" type="key"/>
 <tile id="118" type="bow"/>
 <tile id="119" type="arrow"/>
 <tile id="120" type="slab_bl"/>
 <tile id="121" type="slab_b"/>
 <tile id="122" type="slab_br"/>
 <tile id="127" type="axe"/>
</tileset>
