<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="world" tilewidth="16" tileheight="16" tilecount="215" columns="16">
 <image source="world.png" width="256" height="224"/>
 <tile id="0" type="dirt_0"/>
 <tile id="1" type="grass_0"/>
 <tile id="2" type="ruin_floor_0"/>
 <tile id="3" type="dirt_1"/>
 <tile id="4" type="grass_1"/>
 <tile id="5" type="ruin_floor_1"/>
 <tile id="6" type="dirt_2"/>
 <tile id="7" type="grass_2"/>
 <tile id="8" type="ruin_floor_2"/>
 <tile id="9" type="dirt_3"/>
 <tile id="10" type="grass_3"/>
 <tile id="11" type="ruin_floor_3"/>
 <tile id="12" type="rock_face_0"/>
 <tile id="13" type="ruin_face_0"/>
 <tile id="14" type="rock_face_1"/>
 <tile id="15" type="ruin_face_1"/>
 <tile id="16" type="rock_face_2"/>
 <tile id="17" type="ruin_face_2"/>
 <tile id="18" type="sand_0"/>
 <tile id="19" type="sand_1"/>
 <tile id="20" type="sand_2"/>
 <tile id="21" type="sand_3"/>
 <tile id="22" type="sandstone_face_0"/>
 <tile id="23" type="sandstone_face_1"/>
 <tile id="24" type="sandstone_face_2"/>
 <tile id="25" type="sandstone_face_cracked"/>
 <tile id="26" type="sandstone_top_cracked"/>
 <tile id="27" type="ruin_face_cracked"/>
 <tile id="28" type="ruin_top_cracked"/>
 <tile id="29" type="mud_0"/>
 <tile id="30" type="mud_1"/>
 <tile id="31" type="mud_2"/>
 <tile id="32" type="mud_3"/>
 <tile id="33" type="mossrock_face_0"/>
 <tile id="34" type="mossrock_face_1"/>
 <tile id="35" type="mossrock_face_2"/>
 <tile id="36" type="planks_0"/>
 <tile id="37" type="log_wall_0"/>
 <tile id="38" type="clinic_floor_0"/>
 <tile id="39" type="planks_1"/>
 <tile id="40" type="log_wall_1"/>
 <tile id="41" type="clinic_floor_1"/>
 <tile id="42" type="ice_0"/>
 <tile id="43" type="frost_0"/>
 <tile id="44" type="rime_floor_0"/>
 <tile id="45" type="ice_1"/>
 <tile id="46" type="frost_1"/>
 <tile id="47" type="rime_floor_1"/>
 <tile id="48" type="ice_2"/>
 <tile id="49" type="frost_2"/>
 <tile id="50" type="rime_floor_2"/>
 <tile id="51" type="ice_3"/>
 <tile id="52" type="frost_3"/>
 <tile id="53" type="rime_floor_3"/>
 <tile id="54" type="thin_ice_0"/>
 <tile id="55" type="snowbrick_face_0"/>
 <tile id="56" type="thin_ice_1"/>
 <tile id="57" type="snowbrick_face_1"/>
 <tile id="58" type="glacier_face_0"/>
 <tile id="59" type="glacier_face_1"/>
 <tile id="60" type="glacier_face_2"/>
 <tile id="61" type="icefall"/>
 <tile id="62" type="glacier_face_cracked"/>
 <tile id="63" type="glacier_top_cracked"/>
 <tile id="64" type="bush"/>
 <tile id="65" type="fruit_bush"/>
 <tile id="66" type="fern"/>
 <tile id="67" type="tall_grass"/>
 <tile id="68" type="glowcap"/>
 <tile id="69" type="mushrooms"/>
 <tile id="70" type="rock"/>
 <tile id="71" type="boulder"/>
 <tile id="72" type="bones"/>
 <tile id="73" type="skull"/>
 <tile id="74" type="column_top"/>
 <tile id="75" type="column_base"/>
 <tile id="76" type="column_broken"/>
 <tile id="77" type="tablet"/>
 <tile id="78" type="statue_head"/>
 <tile id="79" type="campfire_0"/>
 <tile id="80" type="campfire_1"/>
 <tile id="81" type="tent_l"/>
 <tile id="82" type="tent_r"/>
 <tile id="83" type="bedroll"/>
 <tile id="84" type="crate"/>
 <tile id="85" type="sign"/>
 <tile id="86" type="note"/>
 <tile id="87" type="chest"/>
 <tile id="88" type="chest_open"/>
 <tile id="89" type="quantum_chest"/>
 <tile id="90" type="teleporter_off"/>
 <tile id="91" type="teleporter_on_0"/>
 <tile id="92" type="teleporter_on_1"/>
 <tile id="93" type="ladder"/>
 <tile id="94" type="vines"/>
 <tile id="95" type="stairs_down"/>
 <tile id="96" type="cave_opening"/>
 <tile id="97" type="ruin_door"/>
 <tile id="98" type="lily_pad"/>
 <tile id="99" type="reeds"/>
 <tile id="100" type="roots"/>
 <tile id="101" type="pot"/>
 <tile id="102" type="valve"/>
 <tile id="103" type="valve_open"/>
 <tile id="104" type="cactus"/>
 <tile id="105" type="cactus_fruit"/>
 <tile id="106" type="dry_bush"/>
 <tile id="107" type="palm"/>
 <tile id="108" type="palm_top"/>
 <tile id="109" type="palm_dead"/>
 <tile id="110" type="palm_dead_top"/>
 <tile id="111" type="cistern"/>
 <tile id="112" type="cistern_full"/>
 <tile id="113" type="stairs_up"/>
 <tile id="114" type="bomb_0"/>
 <tile id="115" type="bomb_1"/>
 <tile id="116" type="sun_crystal"/>
 <tile id="117" type="gate"/>
 <tile id="118" type="gate_open"/>
 <tile id="119" type="council_door"/>
 <tile id="120" type="council_door_open"/>
 <tile id="121" type="lily_big"/>
 <tile id="122" type="lily_sink"/>
 <tile id="123" type="lily_sunk"/>
 <tile id="124" type="willow"/>
 <tile id="125" type="willow_top"/>
 <tile id="126" type="glowmoss"/>
 <tile id="127" type="bell"/>
 <tile id="128" type="skiff"/>
 <tile id="129" type="cauldron_0"/>
 <tile id="130" type="cauldron_1"/>
 <tile id="131" type="shelf"/>
 <tile id="132" type="bed"/>
 <tile id="133" type="surgery_table"/>
 <tile id="134" type="cabinet"/>
 <tile id="135" type="hut_door"/>
 <tile id="136" type="miasma_0"/>
 <tile id="137" type="miasma_1"/>
 <tile id="138" type="shrine"/>
 <tile id="139" type="shrine_lit"/>
 <tile id="140" type="sick_door"/>
 <tile id="141" type="office_door"/>
 <tile id="142" type="sick_door_open"/>
 <tile id="143" type="office_door_open"/>
 <tile id="144" type="pine_top"/>
 <tile id="145" type="pine"/>
 <tile id="146" type="snow_bush"/>
 <tile id="147" type="frozen_grass"/>
 <tile id="148" type="frost_crystal"/>
 <tile id="149" type="brazier"/>
 <tile id="150" type="brazier_lit_0"/>
 <tile id="151" type="brazier_lit_1"/>
 <tile id="152" type="hearth_0"/>
 <tile id="153" type="hearth_1"/>
 <tile id="154" type="ice_block"/>
 <tile id="155" type="frozen_chest"/>
 <tile id="156" type="rune_plate"/>
 <tile id="157" type="watch_gate"/>
 <tile id="158" type="watch_gate_open"/>
 <tile id="159" type="dream_mirror"/>
 <tile id="160" type="dream_bridge"/>
 <tile id="161" type="dream_rune"/>
 <tile id="162" type="frozen_soldier_top"/>
 <tile id="163" type="frozen_soldier"/>
 <tile id="164" type="steam_0"/>
 <tile id="165" type="steam_1"/>
 <tile id="166" type="footprints"/>
 <tile id="167" type="snowdrift"/>
 <tile id="168" type="snowman"/>
 <tile id="169" type="weapon_rack"/>
 <tile id="170" type="veil_0"/>
 <tile id="171" type="veil_1"/>
 <tile id="172" type="cold_lock"/>
 <tile id="173" type="snow_door"/>
 <tile id="174" type="flowers_red"/>
 <tile id="175" type="flowers_yellow"/>
 <tile id="176" type="flowers_white"/>
 <tile id="177" type="tuft_0"/>
 <tile id="178" type="tuft_1"/>
 <tile id="179" type="pebbles_0"/>
 <tile id="180" type="pebbles_1"/>
 <tile id="181" type="leaves"/>
 <tile id="182" type="clover"/>
 <tile id="183" type="mushrooms_small"/>
 <tile id="184" type="twigs"/>
 <tile id="185" type="ripples"/>
 <tile id="186" type="desert_flower"/>
 <tile id="187" type="shards"/>
 <tile id="188" type="dry_twigs"/>
 <tile id="189" type="cattails"/>
 <tile id="190" type="moss"/>
 <tile id="191" type="water_lily"/>
 <tile id="192" type="snow_tuft"/>
 <tile id="193" type="ice_shards"/>
 <tile id="194" type="frost_flower"/>
 <tile id="195" type="rubble"/>
 <tile id="196" type="floor_crack"/>
 <tile id="197" type="moss_face"/>
 <tile id="198" type="roots_face"/>
 <tile id="199" type="crack_face"/>
 <tile id="200" type="icicles_face"/>
 <tile id="201" type="ivy_face"/>
 <tile id="202" type="waterfall_0"/>
 <tile id="203" type="waterfall_1"/>
 <tile id="204" type="log_l"/>
 <tile id="205" type="log_r"/>
 <tile id="206" type="stump"/>
 <tile id="207" type="dead_tree"/>
 <tile id="208" type="snowy_rock"/>
 <tile id="209" type="frozen_log_l"/>
 <tile id="210" type="frozen_log_r"/>
 <tile id="211" type="mossy_log_l"/>
 <tile id="212" type="mossy_log_r"/>
 <tile id="213" type="sun_eye"/>
 <tile id="214" type="sun_eye_open"/>
</tileset>
