name: ✨ Lint, Build & Test

on:
  push:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'clippy.toml'
      - 'cross.toml'
      - 'mise.toml'
      - 'rust-toolchain.toml'
      - 'runtime/**'
      - 'editor/**'
      - 'vectarine-plugin-sdk/**'
      - 'vectarine-plugin-template/**'
      - 'vectarine-cli/**'
  pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
    build_and_test:
        name: ✨ Quality Check
        runs-on: ubuntu-latest
        steps:
            # Version 7 
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
              name: 📂 Checkout
              with:
                  fetch-depth: 1
                  lfs: true # needed for reference screenshots

            # version 1.17.0 In this crazy system, hashes are the only way to pin dependencies
            - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659
              name: ⚙️ Setup Rust
              with:
                  components: clippy, rustfmt
                  target: x86_64-unknown-linux-gnu
                  cache-all-crates: false
                  cache-workspace-crates: false

            - name: ⬇️ Install dependencies
              run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

            - name: 🏗️ Build
              run: cargo build --target=x86_64-unknown-linux-gnu

            - name: 📎 Clippy
              run: cargo clippy --all-targets --all-features --target=x86_64-unknown-linux-gnu

            - name: 🧪 Unit test
              run: cargo test --target=x86_64-unknown-linux-gnu

            - name: 🖼️ Integration test
              id: screenshot_test
              continue-on-error: true
              run: cargo run -p vectarine-cli -- test --path testdata -d 10

            - name: 🖼️ Regenerate screenshots
              id: regenerate_screenshots
              if: ${{ steps.screenshot_test.outcome == 'failure' }}
              run: cargo run -p vectarine-cli -- test --path testdata -r

            # Used to investigate differences in screenshots between local and CI in case of integration test failures.
            - name: 📦 Export test results
              if: ${{ steps.regenerate_screenshots.outcome == 'success' }}
              uses: actions/upload-artifact@v7.0.1
              with:
                retention-days: 1
                name: screenshot-results
                path: testdata
